#
# This is all of combat messages used by combat.c
# Note: all %d values will be filled with a number greater than 1
#
# Truly Generic strings (no need for gender/number issues)
#
{100}{}{Kau perlu %d action points.}
{101}{}{Peluru habis.}
{102}{}{Target diluar jangkauan.}
{103}{}{Pertempuran tak bisa berakhir jika masih ada musuh.}
{104}{}{Bidikanmu terhalang.}
{105}{}{Tak bisa gunakan senjata jika kedua lengan cedera.}
{106}{}{Tak bisa gunakan senjata dua-tangan jika satu lengan cedera.}
{107}{}{Kau tak cukup kuat untuk gunakan senjata ini dengan baik.}
{108}{}{ dan }
#
# Combat Flag Strings (all of these happen to you, MALE player)
#
{200}{}{terkapar}
{201}{}{tersungkur}
{202}{}{mencederai kaki kirimu}
{203}{}{mencederai kaki kananmu}
{204}{}{mencederai lengan kirimu}
{205}{}{mencederai lengan kananmu}
{206}{}{dibutakan}
{207}{}{terbunuh}
{208}{}{kena}
{209}{}{kritis}
{210}{}{terbakar}
{211}{}{baju besimu tertembus}
{212}{}{senjatamu meledak}
{213}{}{senjatamu hancur}
{214}{}{senjatamu jatuh}
{215}{}{kehilangan giliran}
{216}{}{kena diri sendiri}
{217}{}{kehilangan sisa peluru}
{218}{}{peluru tidak mempan}
{219}{}{melukai diri sendiri}
{220}{}{kena secara acak}
{221}{}{cedera organ tubuh acak}
{222}{}{dibumbui serpihan}
#
# Combat Flag Strings (all of these happen to you, FEMALE player)
#
{250}{}{terkapar}
{251}{}{tersungkur}
{252}{}{mencederai kaki kirimu}
{253}{}{mencederai kaki kananmu}
{254}{}{mencederai lengan kirimu}
{255}{}{mencederai lengan kananmu}
{256}{}{dibutakan}
{257}{}{terbunuh}
{258}{}{kena}
{259}{}{kritis}
{260}{}{terbakar}
{261}{}{baju besimu tertembus}
{262}{}{senjatamu meledak}
{263}{}{senjatamu hancur}
{264}{}{senjatamu jatuh}
{265}{}{kehilangan giliran}
{266}{}{kena diri sendiri}
{267}{}{kehilangan sisa peluru}
{268}{}{peluru tidak mempan}
{269}{}{melukai diri sendiri}
{270}{}{kena secara acak}
{271}{}{cedera organ tubuh acak}
{272}{}{dibumbui serpihan}
#
# Combat Flag Strings (all of these happen to a male)
#
{300}{}{terkapar}
{301}{}{tersungkur}
{302}{}{mencederai kaki kirinya}
{303}{}{mencederai kaki kanannya}
{304}{}{mencederai lengan kirinya}
{305}{}{mencederai lengan kanannya}
{306}{}{dibutakan}
{307}{}{terbunuh}
{308}{}{kena}
{309}{}{kritis}
{310}{}{terbakar}
{311}{}{menembus armornya}
{312}{}{senjatanya meledak}
{313}{}{senjatanya hancur}
{314}{}{senjatanya jatuh}
{315}{}{kehilangan gilirannya}
{316}{}{kena dirinya sendiri}
{317}{}{kehilangan sisa pelurunya}
{318}{}{peluru tidak mempan}
{319}{}{melukai dirinya}
{320}{}{kena secara acak}
{321}{}{cedera organ tubuh acak}
{322}{}{dibumbui serpihan}
#
# Combat Flag Strings (all of these happen to a female)
#
{400}{}{terkapar}
{401}{}{tersungkur}
{402}{}{mencederai kaki kirinya}
{403}{}{mencederai kaki kanannya}
{404}{}{mencederai lengan kirinya}
{405}{}{mencederai lengan kanannya}
{406}{}{dibutakan}
{407}{}{terbunuh}
{408}{}{terkena}
{409}{}{kritis}
{410}{}{terbakar}
{411}{}{menembus armornya}
{412}{}{senjatanya meledak}
{413}{}{senjatanya hancur}
{414}{}{senjatanya terjatuh}
{415}{}{kehilangan gilirannya}
{416}{}{kena dirinya sendiri}
{417}{}{hilang sisa pelurunya}
{418}{}{pelurunya tidak mempan}
{419}{}{melukai diri sendiri}
{420}{}{kena secara acak}
{421}{}{cedera organ tubuh acak}
{422}{}{dibumbui serpihan}
#
# Miscellaneous combat messages (all of these happen to you, male player)
# Note: first %s will be replaced by value of line 506, which
#          should be language's equivalent to 2nd person male singular,
#          which is "You" in English. first letter of line 506 should
#          be capitalized, since it will start a sentence.
#       second %s (if there is one) is hit location, which
#          will be a string from section Hit Locations starting
#          in 1000's in this file, with exception of line 509
#          where second %s is name of another creature
{506}{}{Kau}
{509}{}{Oops! %s were hit instead of %s!}
{511}{}{%s were critically hit in %s for %d hit points}
{512}{}{%s were hit in %s for %d hit points}
{513}{}{%s were hit for %d hit points}
{514}{}{%s critically meleset}
{515}{}{%s meleset}
{520}{}{%s were critically hit for %d hit points}
{521}{}{%s were critically hit in %s for 1 hit point}
{522}{}{%s were hit in %s for 1 hit point}
{523}{}{%s were hit for 1 hit point}
{524}{}{%s were critically hit for 1 hit point}
{525}{}{%s were critically hit in %s for no damage}
{526}{}{%s were hit in %s for no damage}
{527}{}{%s were hit for no damage}
{528}{}{%s were critically hit for no damage}
{533}{}{%s critically meleset and took 1 hit point}
{534}{}{%s critically meleset and took %d hit points}
#
# Miscellaneous combat messages (all of these happen to you, female player)
# Note: first %s will be replaced by value of line 556, which
#          should be language's equivalent to 2nd person female singular,
#          which is "You" in English. first letter of line 556 should
#          be capitalized, since it will start a sentence.
#       second %s (if there is one) is hit location, which
#          will be a string from section Hit Locations starting
#          in 1000's in this file, with exception of line 559
#          where second %s is name of another creature
{556}{}{You}
{559}{}{Oops! %s were hit instead of %s!}
{561}{}{%s were critically hit in %s for %d hit points}
{562}{}{%s were hit in %s for %d hit points}
{563}{}{%s were hit for %d hit points}
{564}{}{%s critically meleset}
{565}{}{%s meleset}
{570}{}{%s were critically hit for %d hit points}
{571}{}{%s were critically hit in %s for 1 hit point}
{572}{}{%s were hit in %s for 1 hit point}
{573}{}{%s were hit for 1 hit point}
{574}{}{%s were critically hit for 1 hit point}
{575}{}{%s were critically hit in %s for no damage}
{576}{}{%s were hit in %s for no damage}
{577}{}{%s were hit for no damage}
{578}{}{%s were critically hit for no damage}
{583}{}{%s critically meleset and took 1 hit point}
{584}{}{%s critically meleset and took %d hit points}
#
# Miscellaneous combat messages (all of these happen to a male)
# Note: first %s is name of male creature
#       second %s (if there is one) is hit location, which
#          will be a string from section Hit Locations starting
#          in 1000's in this file, with exception of line 609
#          where second %s is name of another creature
#
{608}{}{Oops! %s was hit instead of you!}
{609}{}{Oops! %s was hit instead of %s!}
{611}{}{%s was critically hit in %s for %d hit points}
{612}{}{%s was hit in %s for %d hit points}
{613}{}{%s was hit for %d hit points}
{614}{}{%s critically meleset}
{615}{}{%s meleset}
{620}{}{%s was critically hit for %d hit points}
{621}{}{%s was critically hit in %s for 1 hit point}
{622}{}{%s was hit in %s for 1 hit point}
{623}{}{%s was hit for 1 hit point}
{624}{}{%s was critically hit for 1 hit point}
{625}{}{%s was critically hit in %s for no damage}
{626}{}{%s was hit in %s for no damage}
{627}{}{%s was hit for no damage}
{628}{}{%s was critically hit for no damage}
{633}{}{%s critically meleset and took 1 hit point}
{634}{}{%s critically meleset and took %d hit points}
#
# Miscellaneous combat messages (all of these happen to a female)
# Note: first %s is name of female creature
#       second %s (if there is one) is hit location, which
#          will be a string from section Hit Locations starting
#          in 1000's in this file, with exception of line 709
#          where second %s is name of another creature
#
{708}{}{Oops! %s was hit instead of you!}
{709}{}{Oops! %s was hit instead of %s!}
{711}{}{%s was critically hit in %s for %d hit points}
{712}{}{%s was hit in %s for %d hit points}
{713}{}{%s was hit for %d hit points}
{714}{}{%s critically meleset}
{715}{}{%s meleset}
{720}{}{%s was critically hit for %d hit points}
{721}{}{%s was critically hit in %s for 1 hit point}
{722}{}{%s was hit in %s for 1 hit point}
{723}{}{%s was hit for 1 hit point}
{724}{}{%s was critically hit for 1 hit point}
{725}{}{%s was critically hit in %s for no damage}
{726}{}{%s was hit in %s for no damage}
{727}{}{%s was hit for no damage}
{728}{}{%s was critically hit for no damage}
{733}{}{%s critically meleset and took 1 hit point}
{734}{}{%s critically meleset and took %d hit points}
#
# Hit Locations (by art_num alias)
#
# regular humans
#
{1110}{}{kepala}
{1111}{}{lengan kiri}
{1112}{}{lengan kanan}
{1113}{}{batang tubuh}
{1114}{}{kaki kanan}
{1115}{}{kaki kiri}
{1116}{}{mata}
{1117}{}{selangkangan}
{1118}{}{uncalled}
#
# Brahmin (Mutant 2-Headed Cows)
#
{1150}{}{kepala}
{1151}{}{kaki kiri belakang}
{1152}{}{kaki kanan belakang}
{1153}{}{batang tubuh}
{1154}{}{kaki kanan depan}
{1155}{}{kaki kiri depan}
{1156}{}{mata}
{1157}{}{kantong susu}
{1158}{}{uncalled}
#
# dogs
#
{1160}{}{kepala}
{1161}{}{kaki depan}
{1162}{}{kaki depan}
{1163}{}{badan}
{1164}{}{kaki kiri}
{1165}{}{kaki kiri}
{1166}{}{mata}
{1167}{}{selangkangan}
{1168}{}{uncalled}
#
# Mr. Handy
#
{1170}{}{CPU}
{1171}{}{manipulator}
{1172}{}{manipulator}
{1173}{}{frame}
{1174}{}{motivator}
{1175}{}{motivator}
{1176}{}{sensors}
{1177}{}{regulator}
{1178}{}{uncalled}
#
# Super Mutants
#
{1180}{}{kepala}
{1181}{}{lengan kiri}
{1182}{}{lengan kanan}
{1183}{}{batang tubuh}
{1184}{}{kaki kanan}
{1185}{}{kaki kiri}
{1186}{}{mata}
{1187}{}{selangkangan}
{1188}{}{uncalled}
#
# Mole-Rat
#
{1190}{}{kepala}
{1191}{}{cakar kiri}
{1192}{}{cakar kanan}
{1193}{}{badan}
{1194}{}{kaki kanan}
{1195}{}{kaki kiri}
{1196}{}{mata}
{1197}{}{selangkangan}
{1198}{}{uncalled}
#
# big humans and mutants
#
{1210}{}{kepala}
{1211}{}{lengan kiri}
{1212}{}{lengan kanan}
{1213}{}{batang tubuh}
{1214}{}{kaki kanan}
{1215}{}{kaki kiri}
{1216}{}{mata}
{1217}{}{selangkangan}
{1218}{}{uncalled}
#
# Radscorpion
#
{1220}{}{kepala}
{1221}{}{ekor}
{1222}{}{cakar}
{1223}{}{cangkang}
{1224}{}{kaki kiri}
{1225}{}{kaki depan}
{1226}{}{mata}
{1227}{}{otak}
{1228}{}{uncalled}
#
# Floater
#
{1230}{}{kepala}
{1231}{}{mulut}
{1232}{}{mulut depan}
{1233}{}{badan}
{1234}{}{float sac}
{1235}{}{ekor}
{1236}{}{ganglion}
{1237}{}{ovipositor}
{1238}{}{uncalled}
#
# masrat? a rat perhaps?
#
{1240}{}{kepala}
{1241}{}{cakar kiri}
{1242}{}{cakar kanan}
{1243}{}{badan}
{1244}{}{kaki kanan}
{1245}{}{kaki kiri}
{1246}{}{mata}
{1247}{}{selangkangan}
{1248}{}{uncalled}
#
# Centaur
#
{1250}{}{kepala}
{1251}{}{lengan kiri}
{1252}{}{lengan kanan}
{1253}{}{badan}
{1254}{}{kaki kanan}
{1255}{}{kaki kiri}
{1256}{}{mata}
{1257}{}{selangkangan}
{1258}{}{uncalled}
#
# human midgets and children
#
{1270}{}{kepala}
{1271}{}{lengan kiri}
{1272}{}{lengan kanan}
{1273}{}{batang tubuh}
{1274}{}{kaki kanan}
{1275}{}{kaki kiri}
{1276}{}{mata}
{1277}{}{selangkangan}
{1278}{}{uncalled}
#
# Overseer
#
{1460}{}{kepala}
{1461}{}{lengan kiri}
{1462}{}{lengan kanan}
{1463}{}{batang tubuh}
{1464}{}{kaki kanan}
{1465}{}{kaki kiri}
{1466}{}{mata}
{1467}{}{selangkangan}
{1468}{}{uncalled}
#
# Gizmo
#
{1490}{}{kepala}
{1491}{}{lengan kiri}
{1492}{}{lengan kanan}
{1493}{}{batang tubuh}
{1494}{}{kaki kanan}
{1495}{}{kaki kiri}
{1496}{}{mata}
{1497}{}{selangkangan}
{1498}{}{uncalled}
#
# Master!
#
{1500}{}{kepala}
{1501}{}{???}
{1502}{}{???}
{1503}{}{frame}
{1504}{}{???}
{1505}{}{???}
{1506}{}{mata}
{1507}{}{CPU}
{1508}{}{uncalled}
#
# Death Claw
#
{1510}{}{kepala}
{1511}{}{lengan kiri}
{1512}{}{lengan kanan}
{1513}{}{batang tubuh}
{1514}{}{kaki kanan}
{1515}{}{kaki kiri}
{1516}{}{mata}
{1517}{}{selangkangan}
{1518}{}{uncalled}
#
# Mantis
#
{1520}{}{kepala}
{1521}{}{raptorial leg}
{1522}{}{raptorial leg}
{1523}{}{abdomen}
{1524}{}{legs}
{1525}{}{wings}
{1526}{}{mata}
{1527}{}{metathorax}
{1528}{}{uncalled}
#
# Robobrain
#
{1530}{}{CPU}
{1531}{}{manipulator}
{1532}{}{manipulator}
{1533}{}{frame}
{1534}{}{motivator}
{1535}{}{motivator}
{1536}{}{sensors}
{1537}{}{regulator}
{1538}{}{uncalled}
#
# Eyeball (Robot)
#
{1540}{}{CPU}
{1541}{}{manipulator}
{1542}{}{manipulator}
{1543}{}{frame}
{1544}{}{motivator}
{1545}{}{motivator}
{1546}{}{sensors}
{1547}{}{regulator}
{1548}{}{uncalled}
#
# Mutant Pig Rat (small Mole-Rat)
#
{1550}{}{kepala}
{1551}{}{cakar kiri}
{1552}{}{cakar kanan}
{1553}{}{badan}
{1554}{}{kaki kanan}
{1555}{}{kaki kiri}
{1556}{}{mata}
{1557}{}{selangkangan}
{1558}{}{uncalled}
#
# Deathclaw Egg
#
{1580}{}{shell}
{1581}{}{shell}
{1582}{}{shell}
{1583}{}{shell}
{1584}{}{shell}
{1585}{}{shell}
{1586}{}{shell}
{1587}{}{shell}
{1588}{}{uncalled}

#
# Critical Hit Messages
#
# 5000 series - men (including generics)
#
{5000}{}{ dan sangat menyakitkan}
{5001}{}{. Menimbulkan luka yang serius}
{5002}{}{ tanpa pertahanan armor}
{5003}{}{. serangan itu membuat dia pingsan}
{5004}{}{. serangan itu membuatnya jatuh ke tanah}
{5005}{}{. serangan keras ke kepala membuatnya pingsan}
{5006}{}{. attack crushes temple. Good night, Gracie}
{5007}{}{, death is instantaneous}
{5008}{}{, causing severe tennis elbow}
{5009}{}{, pushing arm out of way}
{5010}{}{, leaving a big bruise}
{5011}{}{, crippling lengan kiri}
{5012}{}{, leaving lengan kiri dangling by skin}
{5013}{}{. That arm now looks like a bloody stump}
{5014}{}{, leaving a crippled right arm}
{5015}{}{. His right arm is pulverized by this powerful blow}
{5016}{}{ in a forceful blow}
{5017}{}{ blowing through armor}
{5018}{}{, inflicting an extra helping of damage}
{5019}{}{ with no armor, knocking combatant to ground}
{5020}{}{ knocking air out, he slumps to ground out of fight}
{5021}{}{. Unfortunately, his spine is now clearly visible from front}
{5022}{}{ putting a major hurt on his leg}
{5023}{}{, knocking him to ground like a bowling pin in a league game}
{5024}{}{, bowling him over and crippling that leg}
{5025}{}{, smashing knee into next town. He falls}
{5026}{}{. intense pain of having a leg removed causes him to quit}
{5027}{}{ inflicting some extra pain}
{5028}{}{ causing blindness, unluckily for him}
{5029}{}{, and with no protection there, causing serious pain}
{5030}{}{, and blinding him with a stunning blow}
{5031}{}{. loss of an eye is too much for him, and he falls to ground}
{5032}{}{, sadly, he is too busy feeling rush of air on brain to notice death approaching}
{5033}{}{. Ouch! That had to hurt}
{5034}{}{, and he's not wearing a cup, either}
{5035}{}{ and without protection, he falls over, groaning in agony}
{5036}{}{. pain is too much for him and he collapses like a rag}
{5037}{}{. He mumbles "Mother", as his eyes roll into back of his head}
#
# series 5100 - women
#
{5100}{}{ and really hurts}
{5101}{}{. A serious wound is inflicted}
{5102}{}{ with no armor}
{5103}{}{. damaging attack knocks her unconscious}
{5104}{}{. blow knocks her to ground}
{5105}{}{. strong blow to kepala knocks her out}
{5106}{}{. attack crushes her temple. Good night, Gracie}
{5107}{}{, death is instantaneous}
{5108}{}{, causing severe tennis elbow}
{5109}{}{, pushing arm out of way}
{5110}{}{, leaving a big bruise}
{5111}{}{, crippling lengan kiri}
{5112}{}{. lengan kiri is barely attached to her shoulder}
{5113}{}{. That arm now looks like a bloody stump}
{5114}{}{, leaving a crippled right arm}
{5115}{}{. Her right arm is turned into hamburger by blow}
{5116}{}{ in a forceful blow}
{5117}{}{ piercing through her defenses}
{5118}{}{, inflicting an extra helping of damage}
{5119}{}{ with no armor, knocking female fighter to ground}
{5120}{}{ knocking air out, she slumps to ground}
{5121}{}{. Unfortunately, her major organs have been exposed to light}
{5122}{}{ putting a major hurt on her leg}
{5123}{}{, knocking her over like a bad blind date}
{5124}{}{, knocking her down and crippling that leg}
{5125}{}{, smashing knee into next town. She takes fast track to ground}
{5126}{}{. She screams in pain from broken leg}
{5127}{}{ inflicting some extra pain}
{5128}{}{ causing blindness. She grimaces}
{5129}{}{, and with no protection there, causing serious pain}
{5130}{}{. wound causes severe blindness, as if there is any other kind}
{5131}{}{. She faints from blinding attack}
{5132}{}{, sadly, she doesn't get to pray to her gods before she meets them}
{5133}{}{. She takes it like a man. That is to say, it hurts}
{5134}{}{, knocking her to ground}
{5135}{}{. Her childbearing days are in trouble as she collapses in a limp heap}
#
# series 5200 - children
#
{5200}{}{. little kid starts to cry}
{5201}{}{. Unconscious, small child falls over}
{5202}{}{. Ouchie!}
{5203}{}{. blow is true, and child is knocked unconscious}
{5204}{}{, smashing small child around like a limp rag}
{5205}{}{. lengan kiri of this kid now has an owie}
{5206}{}{, throwing small child off balance}
{5207}{}{, breaking that arm with a loud snap. Some serious tears start to flow}
{5208}{}{, easily snapping that arm like a small piece of candy}
{5209}{}{. lengan kanan starts to swell, like a balloon}
{5210}{}{, and starts to cry}
{5211}{}{ in a sensitive spot}
{5212}{}{. attack to a vital organ knocks kid over}
{5213}{}{, knocking little kid over like a toy}
{5214}{}{. Now this young child will never really experience life}
{5215}{}{, inflicting a deep cut}
{5216}{}{. attack bowls child over, and breaks leg}
{5217}{}{, inflicting great harm to small child}
{5218}{}{. young child looks up and starts to cry}
{5219}{}{, which blinds youth}
{5220}{}{, bashing in youthful looking nose}
{5221}{}{. A cut appears above mata and blood starts to flow freely}
{5222}{}{, which opens an eye like an exploding grape. child looks bewildered}
{5223}{}{ causing blindness. young child drops to ground}
{5224}{}{, blow continues into small brain}
{5225}{}{. child looks confused and shaken}
{5226}{}{, knocking this young target to ground}
#
# series 5300 - Super Mutants
#
{5300}{}{, hurting mighty mutant}
{5301}{}{, striking a vital spot}
{5302}{}{, striking a vital spot and knocking giant to ground}
{5303}{}{. giant mutant looks around for a moment, and then slumps to ground}
{5304}{}{. kepala explodes like a giant, bloody watermelon}
{5305}{}{, severely hurting mighty mutant}
{5306}{}{, causing giant to spend a moment cursing universe}
{5307}{}{, striking a nerve and forcing giant to grab his arm in pain}
{5308}{}{. blow breaks elbow and probably didn't feel too good}
{5309}{}{, breaking thick arm and spewing mutant blood over ground}
{5310}{}{, causing giant to stumble for a moment and then collapse like a felled tree}
{5311}{}{, and gallons of viscera splurt to ground}
{5312}{}{, sending giant flying to floor}
{5313}{}{. mutant stumbles and falls, his leg barely able to support him}
{5314}{}{, striking a vital location. mutant crumples under a broken leg}
{5315}{}{. pain of a broken leg overwhelms mighty giant}
{5316}{}{, nearly blinding mutant}
{5317}{}{, blinding now-furious mutant}
{5318}{}{, nearly blinding mutant but throwing him off balance}
{5319}{}{. blinded mutant stumbles back, unprepared for next attack}
{5320}{}{, blinding now-unconscious mutant}
{5321}{}{. mata of mutant glow for a moment, and then light fades - permanently}
#
# series 5400 - Ghouls
#
{5400}{}{. ghoul is surprised, and fails to defend against this attack}
{5401}{}{. This blow buries this ghoul}
{5402}{}{. stunned ghoul's hand flies open}
{5403}{}{, sneaking through his armor and striking a critical joint}
{5404}{}{, sneaking through his armor and lopping arm off}
{5405}{}{. ghoul moves wrong way at wrong moment, and loses an eye}
{5406}{}{. ghoul is wearing no armor there}
{5407}{}{, and without armor, ghoul is blinded}
{5408}{}{, causing ghoul to look bewildered in his final moments}
#
# series 5500 - Brahmin
#
{5500}{}{, knocking big beast to ground}
{5501}{}{, stunning both brains and felling giant animal}
{5502}{}{. mutant cow gives a loud, startled cry}
{5503}{}{, breaking one of Brahmin's legs}
{5504}{}{, seriously hurting mutant cow}
{5505}{}{, easily penetrating thick hide of giant beast}
{5506}{}{, penetrating straight through both hearts of mutant cow}
{5507}{}{, blinding both sets of eyes with a single blow}
{5508}{}{, blinding both heads and stunning mutant cow}
{5509}{}{, completely blinding Brahmin and knocking it out}
{5510}{}{, large mutant bovine stumbles for a moment}
{5511}{}{. Brahmin shakes with rage}
{5512}{}{. Brahmin snorts with pain}
{5513}{}{. Brahmin is most upset with this udderly devastating attack}
#
# series 5600 - Radscorpions
#
{5600}{}{, sending Radscorpion flying on it's back}
{5601}{}{, separating kepala from carapace}
{5602}{}{, seriously damaging tail}
{5603}{}{, putting a major hurt on it's claws}
{5604}{}{. blow slips between cracks of Radscorpion's tough carapace}
{5605}{}{, striking through tough carapace without pausing}
{5606}{}{, passing through natural armor and knocking Radscorpion over}
{5607}{}{. Radscorpion cannot cope with a new sensation, like missing internal organs}
{5608}{}{, sending 'scorpion flying and crippling some of it's legs}
{5609}{}{. attack cuts through an unprotected joint on leg, severing it}
{5610}{}{, seriously wounding and blinding mutant creature}
{5611}{}{, penetrating almost to brain. Talk about squashing a bug}
{5612}{}{, almost penetrating to brain, but blinding creature instead}
{5613}{}{. attack is fiendish, and far too sophisticated for this simple creature}
{5614}{}{. If it was human, you would swear it's pretty pissed off}
{5615}{}{, knocking poor creature senseless}
{5616}{}{, spiking brain to floor}
#
# series 5700 - Rats
#
{5700}{}{. rodent's skull makes several unhealthy sounds}
{5701}{}{, squashing rodent's skull like a wet paper bag}
{5702}{}{, and cakar kiri now looks a little flat}
{5703}{}{. cakar kiri of rat is blown off}
{5704}{}{. cakar kanan is heavily damaged}
{5705}{}{, blowing cakar kanan off}
{5706}{}{. rat is seriously wounded by this attack}
{5707}{}{, seriously wounding rat and knocking it around}
{5708}{}{, splattering rat across floor}
{5709}{}{, crippling kaki kanan}
{5710}{}{, putting a big hole in kaki kiri}
{5711}{}{, doing some extra damage due to sensitive location}
{5712}{}{, summoning this creature to great ratcatcher in sky}
#
# series 5800 - Floaters
#
{5800}{}{, floater drops to ground}
{5801}{}{, floater falls to ground, seemingly lifeless}
{5802}{}{, with serious consequences to creatures continued existance}
{5803}{}{, stunning foul creature}
{5804}{}{, hitting a sensitive spot there and stunning floater}
{5805}{}{. blow causes floater to shudder violently in a spray of crimson}
{5806}{}{, blow causing some sort of violent reaction in creature}
{5807}{}{. floater suddenly bursts into flames}
{5808}{}{ then it jerks wildly and quivers like a pudding surprise}
{5809}{}{, with blow hitting a sensitive spot}
{5810}{}{. creature is obviously agitated}
#
# series 5900 - Centaurs
#
{5900}{}{, pushed like a bad habit, centaur falls over and is stunned}
{5901}{}{ as blow strikes a critical spot}
{5902}{}{, causing a massive neurological failure}
{5903}{}{, stunning it with your violent attack}
{5904}{}{, crippling arm}
{5905}{}{ striking a critical spot, and crippling arm}
{5906}{}{, knocking creature over and crippling leg}
{5907}{}{, stunning centaur as it is knocked over with a crippled leg}
{5908}{}{, blinding a head}
{5909}{}{, surprising centaur. It blindly stumbles for a moment}
{5910}{}{, surprising centaur. It collapses in a heap}
{5911}{}{, surprising centaur. It collapses in a pile of goo}
{5912}{}{. attack was not as effective as it could have been}
#
# series 6000 - Robots
#
{6000}{}{, inflicting some structural damage}
{6001}{}{, sparks fly and robot goes momentarily out of control}
{6002}{}{, hitting a critical component and forcing robot out of control}
{6003}{}{, hitting a critical component and causing a massive malfunction}
{6004}{}{. robot attempts to compensate}
{6005}{}{. robot strains to compensate}
{6006}{}{, hitting some key part and causing heavy damage}
{6007}{}{, inflicting heavy structural damage}
{6008}{}{, hitting a critical component and causing severe damage}
{6009}{}{. robot shudders under this intense attack}
{6010}{}{, dismantling robot}
{6011}{}{. robot attempts to compensate, but fails, falling to ground}
{6012}{}{. robot strains under pressure, falling to ground}
{6013}{}{, breaking sensor lenses}
#
# series 6100 - Dogs
#
{6100}{}{, knocking pooch to ground}
{6101}{}{, right across snout}
{6102}{}{. dog falls over, but it is still breathing}
{6103}{}{, animal coughs up a splurt of blood}
{6104}{}{, crippling leg}
{6105}{}{, crippling leg. animal tries to remain standing, but fails}
{6106}{}{. blinded animal howls in pain}
{6107}{}{, neutering poor animal}
#
# series 6200 - Manti
#
{6200}{}{, knocking down this mutated insect}
{6201}{}{, which collapses}
{6202}{}{. manti ponders whether to continue living}
{6203}{}{, crippling limb}
{6204}{}{, causing Manti to lick it's wounds. It holds limb oddly}
{6205}{}{, bypassing chitinous armor}
{6206}{}{. manti shrieks and shivers must unhuman like}
{6207}{}{, which causes manti to fall over. A limb is bent at an odd shape}
{6208}{}{, shredding wings}
{6209}{}{, bypassing chitinous armor and throwing manti around}
{6210}{}{, blinding insect with an accurate blow}
#
# series 6300 - Deathclaw
#
{6300}{}{. Even this beast seems fazed by that stunning attack}
{6301}{}{, slipping past huge claws to strike monster. Deathclaw shakes and growls}
{6302}{}{. result is massive damage to Deathclaw's eyes}
#
# series 6400 - Master
#
{6400}{}{, breaking past bio-organic defenses}
{6401}{}{, causing Master some serious grief}
{6402}{}{, breaking past bio-organic defenses and putting pressure on Master}
{6403}{}{, stunning Master with a solid offensive plan}
{6404}{}{, causing an overload of cataclysmic proportions in Master's systems}
{6405}{}{. attack against Master seems to do less damage than it should have}
{6406}{}{. blow gets by bio-organic defenses, actually blinding Master}
#
# series 6500 - Player
#
{6500}{}{. You'll have a headache tomorrow, if you live that long}
{6501}{}{. Your armor provides no protection from this well-aimed blow}
{6502}{}{. You feel pain for just a moment, and then darkness takes you..}
{6503}{}{, bypassing your armor. blow knocks you off your feet}
{6504}{}{, shock makes your vision go dark. After a moment, you notice that your vision has not returned}
{6505}{}{. You get a nice view of your body as your head sails through air}
{6506}{}{. Surprisingly, damage feels no worse than normal}
{6507}{}{, stunning you for a moment}
{6508}{}{. Feel pain}
{6509}{}{. attack leaves your arm useless}
{6510}{}{, slipping past your armor. blow cracks bones in your arm like deadwood}
{6511}{}{, bypassing your armor. Your arm now hangs limply at your side}
{6512}{}{. bruise will look nice, and maybe scars will make good party talk}
{6513}{}{, crushing your internal organs. All you can do is gurgle blood}
{6514}{}{, sending head over heels}
{6515}{}{, sending you flying and breaking your leg}
{6516}{}{, melting through your armor. blow knocks you over and seriously hurts your knee}
{6517}{}{. pain from your broken leg sends you into unconsciousness}
{6518}{}{. painful blow makes you flinch, but does little else}
{6519}{}{. Unlucky for you, it also causes immediate vision loss}
{6520}{}{. It takes you a moment to wipe blood from your eyes}
{6521}{}{, slipping past your armor. You stand stunned as your realize you cannot see anymore}
{6522}{}{. You feel a strange sensation in your head. You realize it's imminent brain-death}
{6523}{}{, making you cringe}
{6524}{}{. You cup your groin and fall to floor in pain}
{6525}{}{. pain is sufficient to knock you out. Ouch}
{6526}{}{. There are not enough words in universe to describe pain your are feeling at this moment}
