#
# Item.c messages
#
{1}{}{Kau mendapatkan %d %s.}
{2}{}{Kau kehilangan %d %s.}
{3}{}{Kau merasa lebih baik.}
{4}{}{Kau menderita serangan jantung fatal karena overdosis chem.}
{5}{}{%s tak ada muatan daya tersisa.}
{6}{}{%s menyala.}
{7}{}{%s mati.}
{8}{}{Kau mengarahkan Geiger counter ke tubuhmu. Counternya menunjukkan: %d}
{9}{}{Item ini hanya bisa digunakan dari interface bar.}
{10}{}{Tidak terjadi apa-apa.}
