#
# Miscellaneous game engine messages.
#
# Defined in game.h
#
{0}{}{Apa kau yakin ingin keluar?}
{1}{}{Demo version}
{2}{}{Default character will be used.}
{3}{}{Saved screenshot.}
{4}{}{Quick load game successfully loaded.}
{5}{}{Quick save game successfully saved.}
{6}{}{Demo time limit exceeded.}
{7}{}{Pipboy not available in combat!}
{8}{}{Error saving screenshot.}
{9}{}{INTRO}
{10}{}{BUAT BARU}
{11}{}{MUAT GAME}
{12}{}{KREDIT}
{13}{}{KELUAR}
{14}{}{Copyright(c) 1997 Interplay Productions.  All rights reserved.}
{15}{}{Action Points}
{16}{}{Hit Points}
{17}{}{The motion sensor option is not installed.}
{18}{}{The motion sensor has no charges remaining.}
#
# Game config text. Defined in gconfig.c
#
{100}{}{Error saving game config file!}
{101}{}{Game settings not saved.}
#
# Some radiation messages used in critter.c
#
{1000}{}{You feel very nauseous.}
{1001}{}{You feel very nauseous, and after some mild vomiting, slightly fatigued.}
{1002}{}{You are very fatigued, the vomiting does not stop, and your recovery time is impaired.}
{1003}{}{You are hemorrhaging violently. You are very sick, and your hair is falling out.}
{1004}{}{You are hemorrhaging violently and continuously. The vomitus is stained red from your blood. Your skin is falling off of your bones.}
{1005}{}{There is bleeding from your intestines and you have severe diarrhea. You feel bloated and are in intense agony.}
{1006}{}{You have died from radiation sickness.}
{1007}{}{Kau menerima dosis radiasi yang sangat besar.}
{1008}{}{Geiger counter-nya berbunyi.}
{1009}{}{Geiger counter-nya berbunyi tidak karuan.}
#
# Message used in actions.c
#
{2000}{}{Kau tidak bisa kesana.}
{2001}{}{Kunci gemboknya macet.}
#
# poison messages from critter.c
#
{3000}{}{Kau sudah kena racun!}
{3001}{}{Kau merasakan efek dari racun.}
#
# from queue.c
#
{4000}{}{Karna penangananmu yang ceroboh, bom itu meledak sebelum waktunya.}
#
# from combatai.c
#
{5000}{}{menggunakan}
{5001}{}{peluru sudah habis untuk}
{5002}{}{mengisi ulang}
#
# from gdialog.c - new tell me about stuff
#
{6000}{}{Mau tanya apa?}
